### ISSUE TITLE
Generating a content type fails

### ISSUE THREAD

**Issue by did** [locomotivecms/wagon#224]
From a locomotive user:

"There is an error in loco website:http://doc.locomotivecms.com/making-blog/3-5-related-types

When I try to run this command:
bundle exec wagon generate content_type photos caption:string file:file:required post:belongs_to:required

I got an error:
gardian@vaio ~/Developing/bootstrap $ bundle exec wagon generate content_type photos1 caption photo_file:file:true
       exist  
      create  app/content_types/photos1.yml
      create  data/photos1.yml
gardian@vaio ~/Developing/bootstrap $ bundle exec wagon generate content_type photos caption photo_file:file:true post:belongs_to:true
/var/lib/gems/1.9.1/gems/locomotivecms_wagon-1.5.1/lib/locomotive/wagon/generators/content_type.rb:51:in `block (2 levels) in extract_fields': undefined method `singularize' for nil:NilClass (NoMethodError)"

**Comment by Valish** [comment]
I ran into this bug as well, running the same command:

**v:~/src/demo/locomotive/engine/demo$ bundle exec wagon generate content_type photos caption:string file:file:required post:belongs_to:required**
```                      
/home/valish/.rvm/gems/ruby-2.1.5/gems/locomotivecms_wagon-1.5.2/lib/locomotive/wagon/generators/content_type.rb:54:in `block (2 levels) in extract_fields': undefined method `singula
rize' for nil:NilClass (NoMethodError)
        from /home/valish/.rvm/gems/ruby-2.1.5/gems/locomotivecms_wagon-1.5.2/lib/locomotive/wagon/generators/content_type.rb:50:in `tap'
        from /home/valish/.rvm/gems/ruby-2.1.5/gems/locomotivecms_wagon-1.5.2/lib/locomotive/wagon/generators/content_type.rb:50:in `block in extract_fields'
        from /home/valish/.rvm/gems/ruby-2.1.5/gems/locomotivecms_wagon-1.5.2/lib/locomotive/wagon/generators/content_type.rb:41:in `map'
        from /home/valish/.rvm/gems/ruby-2.1.5/gems/locomotivecms_wagon-1.5.2/lib/locomotive/wagon/generators/content_type.rb:41:in `extract_fields'
        from /home/valish/.rvm/gems/ruby-2.1.5/gems/locomotivecms_wagon-1.5.2/lib/locomotive/wagon/generators/content_type.rb:26:in `copy_sources'
        from /home/valish/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/valish/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/valish/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `block in invoke_all'
        from /home/valish/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `each'
        from /home/valish/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `map'
        from /home/valish/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:133:in `invoke_all'
        from /home/valish/.rvm/gems/ruby-2.1.5/gems/locomotivecms_wagon-1.5.2/lib/locomotive/wagon.rb:148:in `generate'
        from /home/valish/.rvm/gems/ruby-2.1.5/gems/locomotivecms_wagon-1.5.2/lib/locomotive/wagon/cli.rb:82:in `content_type'
        from /home/valish/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/valish/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/valish/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/valish/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from /home/valish/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
        from /home/valish/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /home/valish/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /home/valish/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /home/valish/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /home/valish/.rvm/gems/ruby-2.1.5/gems/locomotivecms_wagon-1.5.2/bin/wagon:12:in `<top (required)>'
        from /home/valish/.rvm/gems/ruby-2.1.5/bin/wagon:23:in `load'
from /home/valish/.rvm/gems/ruby-2.1.5/bin/wagon:23:in `<main>'
        from /home/valish/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
        from /home/valish/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'

```

Line where the error occurs:
**~/.rvm/gems/ruby-2.1.5/gems/locomotivecms_wagon-1.5.2/lib/locomotive/wagon/generators/content_type.rb:54**: 
```
inverse_of = type == 'belongs_to' ? target_content_type_slug.singularize : target_content_type_slug
```

Happening inside method `extract_fields(fields)`:
```
        def extract_fields(fields)
          fields.map do |raw_attributes|
            name, type, label, required, localized, target_content_type_slug  = raw_attributes.split(':')

            OpenStruct.new(
              name:       name,
              label:      label || name.humanize,
              type:       type || 'string',
              required:   %w(true required).include?(required),
              localized:  %w(true localized).include?(localized)
            ).tap do |field|
              if %w(belongs_to has_many many_to_many).include?(type)
                field.class_name = target_content_type_slug

                inverse_of = type == 'belongs_to' ? target_content_type_slug.singularize : target_content_type_slug

                field.inverse_of = inverse_of
              end
            end
          end
        end
```

**Comment by did** [comment]
hey @Valish, I'm not sure about the syntax you used to create your content type including a relationship with another content type.
Anyway, actually, I've implemented a new generator in Wagon 1.5.2 in order to generate a relationship (belongs_to, has_many, many_to_many) between 2 content types.
So, the plan is to, first, create the content types WITHOUT specifying any fields related to another content type. Then, in a second time, use the "relationship" generator (wagon generate help relationship for more information), to create those relationships. 
I have to update the documentation as well.

**Comment by lutzjs** [comment]
Has this issue ever been resolved? I'm navigating through the create a blog tutorial and I'm continuing to get an error on 3.5 when trying to create related types. I have looked through the online documentation and still can't seem to find the answer

**Comment by did** [comment]
hi @lutzjs, 

I changed the way to create a relationship between 2 content types as mentioned above. Here is the new way:

1/ update to Wagon >= 1.5.2

2/ create your 2 content types without any relationship fields

3/ type the command:

   "wagon generate relationship photos belongs_to posts

I've not had a chance to update the documentation.

**Comment by lutzjs** [comment]
Didier,

Thank you so much for the response, I’ve been really interested in LocomotiveCMS for quite some time, and finally I’m getting the opportunity to explore it. I’m very impressed, but definitely needed the ability to create relationships between content types. The instructions you provided made sense, so I’ll give that a try. Thanks again.

Jonathan

**Comment by sbroways** [comment]
Had the same problem. This worked perfectly. You may want to update the blog tutorial when you get a chance. I ran into several similar issues where Wagon has been updated to function a little different from what's outlined in the tutorial. It's a great product overall and very easy to use. Thanks for the open source contribution.
